apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-desk.fullname" . }}-db
  labels:
    {{- include "ai-desk.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ExternalName
  externalName: {{ .Values.database.host }}
