spring:
  application:
    name: ai-desk
  profiles:
    active: dev

mybatis:
  mapper-locations:
    - classpath*:mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: NULL
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
