-- =====================================================================
-- AI Desk 스키마
-- t_user / t_refresh_token 을 먼저 정의 — t_ai_agent.owner_account_sn 등이 참조.
-- =====================================================================

-- =====================================================================
-- 사용자 인증 (멀티유저 도입 — sample/backend_spring 패턴 동일)
-- =====================================================================

CREATE TABLE IF NOT EXISTS t_user (
    account_sn    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id      VARCHAR(255) NOT NULL UNIQUE,
    password      VARCHAR(255) NOT NULL,
    display_name  VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',
    last_login_dt TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  t_user               IS 'AI Desk 사용자 계정. 자체 인증 (BCrypt + JWT).';
COMMENT ON COLUMN t_user.account_sn    IS '사용자 PK. JWT accountSn 클레임에 그대로 노출';
COMMENT ON COLUMN t_user.login_id      IS '로그인 식별자. email 값을 lowercase 정규화해 저장';
COMMENT ON COLUMN t_user.password      IS 'BCrypt 해시';
COMMENT ON COLUMN t_user.display_name  IS '대시보드/채팅에 노출되는 표시명. 회원가입 시 login_id 값으로 자동 세팅. 향후 사용자 변경 가능 여지로 컬럼은 유지.';
COMMENT ON COLUMN t_user.role          IS '권한 역할. 1단계 모두 USER. ADMIN 등 확장 가능';
COMMENT ON COLUMN t_user.last_login_dt IS '마지막 로그인 시각 (감사 용도)';

CREATE TABLE IF NOT EXISTS t_refresh_token (
    token_sn    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_sn  BIGINT       NOT NULL REFERENCES t_user(account_sn) ON DELETE CASCADE,
    login_id    VARCHAR(255) NOT NULL,
    family_id   VARCHAR(36)  NOT NULL,
    jti         VARCHAR(36)  NOT NULL UNIQUE,
    token_hash  VARCHAR(64)  NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked_yn  CHAR(1)      NOT NULL DEFAULT 'N',
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_refresh_account ON t_refresh_token (account_sn);
CREATE INDEX IF NOT EXISTS ix_refresh_family  ON t_refresh_token (family_id);

COMMENT ON TABLE  t_refresh_token             IS 'refresh JWT 회전 추적. family/jti/revoked_yn 로 reuse 감지';
COMMENT ON COLUMN t_refresh_token.family_id   IS '한 번의 로그인으로 시작된 회전 사슬 ID (UUID)';
COMMENT ON COLUMN t_refresh_token.jti         IS '발급된 refresh JWT 의 jti 클레임 (UUID)';
COMMENT ON COLUMN t_refresh_token.token_hash  IS 'refresh raw 의 SHA-256 — DB 유출 시 원본 보호';
COMMENT ON COLUMN t_refresh_token.revoked_yn  IS 'Y 면 폐기. 폐기 후 같은 jti 재사용 = reuse 감지';

-- AI Desk PostgreSQL 스키마
-- 적용: docker exec -i postgres-db psql -U postgres -d aidesk < backend/src/main/resources/db/schema.sql

-- =====================================================================
-- t_ai_agent — AI 에이전트
-- =====================================================================
CREATE TABLE IF NOT EXISTS t_ai_agent (
    agent_id          VARCHAR(36)  PRIMARY KEY,
    owner_account_sn  BIGINT       NOT NULL REFERENCES t_user(account_sn) ON DELETE CASCADE,
    agent_name        VARCHAR(50)  NOT NULL,
    workspace_dir     VARCHAR(500) NOT NULL,
    tmux_session      VARCHAR(80)  NOT NULL,
    status            VARCHAR(10)  NOT NULL,
    task_desc         VARCHAR(200),
    model             VARCHAR(50)  NOT NULL,
    context_pct       INTEGER,
    bootstrap_applied BOOLEAN      NOT NULL DEFAULT FALSE,
    started_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ,
    deleted_at        TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_agent_owner ON t_ai_agent (owner_account_sn);
COMMENT ON COLUMN t_ai_agent.owner_account_sn IS '에이전트 소유 사용자 (t_user.account_sn). 모든 조회/생성/삭제가 본인 것만.';

COMMENT ON TABLE  t_ai_agent IS 'AI 에이전트 인스턴스';
COMMENT ON COLUMN t_ai_agent.agent_id          IS '에이전트 UUID (PK)';
COMMENT ON COLUMN t_ai_agent.agent_name        IS 'AI 이름';
COMMENT ON COLUMN t_ai_agent.workspace_dir     IS '워크스페이스 절대 경로';
COMMENT ON COLUMN t_ai_agent.tmux_session      IS 'last mile 주입용 tmux 세션명';
COMMENT ON COLUMN t_ai_agent.status            IS '상태 active / idle / done';
COMMENT ON COLUMN t_ai_agent.task_desc         IS '현재 수행 작업 설명';
COMMENT ON COLUMN t_ai_agent.model             IS '사용 모델 풀네임';
COMMENT ON COLUMN t_ai_agent.context_pct       IS '컨텍스트 사용률 0~100';
COMMENT ON COLUMN t_ai_agent.bootstrap_applied IS '부트스트랩 프롬프트(workrole 학습)를 이 에이전트에 한 번이라도 주입했는지. 첫 [터미널 열기] 시 주입 후 true';
COMMENT ON COLUMN t_ai_agent.deleted_at        IS '소프트 딜리트 시각, NULL = 미삭제';

CREATE INDEX IF NOT EXISTS idx_ai_agent_status
    ON t_ai_agent (status, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_agent_deleted
    ON t_ai_agent (deleted_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_ai_agent_tmux_session
    ON t_ai_agent (tmux_session) WHERE deleted_at IS NULL;

-- 휴먼 entity 는 *user 별 1 row* 로 LoginService.signup() 에서 자동 생성.
-- tmux_session = '__human__:<account_sn>' 형식. model = 'human'.
-- backend / helper 가 이 row 를 만나면 send-keys skip + 즉시 delivered.

-- =====================================================================
-- t_ai_message — AI 협업 메시지
-- =====================================================================
CREATE TABLE IF NOT EXISTS t_ai_message (
    message_id           VARCHAR(36)   PRIMARY KEY,
    from_agent_id        VARCHAR(36)   NOT NULL,
    to_agent_id          VARCHAR(36)   NOT NULL,
    content              VARCHAR(1000) NOT NULL,
    reply_to_message_id  VARCHAR(36),
    root_message_id      VARCHAR(36),
    hop_count            INTEGER       NOT NULL DEFAULT 0,
    status               VARCHAR(15)   NOT NULL,
    error_reason         VARCHAR(200),
    retry_count          INTEGER       NOT NULL DEFAULT 0,
    last_attempt_at      TIMESTAMPTZ,
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
    delivered_at         TIMESTAMPTZ,
    read_at              TIMESTAMPTZ,
    replied_at           TIMESTAMPTZ
);
-- 기존 DB 호환 (이미 만들어진 테이블에 column 추가)
ALTER TABLE t_ai_message ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE t_ai_message ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMPTZ;

COMMENT ON TABLE  t_ai_message IS 'AI 에이전트 간 메시지';
COMMENT ON COLUMN t_ai_message.message_id           IS '메시지 UUID (PK)';
COMMENT ON COLUMN t_ai_message.from_agent_id        IS '보낸 AI (FK → t_ai_agent)';
COMMENT ON COLUMN t_ai_message.to_agent_id          IS '받는 AI (FK → t_ai_agent)';
COMMENT ON COLUMN t_ai_message.content              IS '본문 (최대 1000자)';
COMMENT ON COLUMN t_ai_message.reply_to_message_id  IS '답장 체인 — 원본 메시지 ID';
COMMENT ON COLUMN t_ai_message.root_message_id      IS '체인 루트 메시지 (자기 자신이면 NULL)';
COMMENT ON COLUMN t_ai_message.hop_count            IS '위임 깊이 (기본 0, 답장이면 부모+1)';
COMMENT ON COLUMN t_ai_message.status               IS 'sent / delivered / replied / failed';
COMMENT ON COLUMN t_ai_message.error_reason         IS 'failed 사유';
COMMENT ON COLUMN t_ai_message.retry_count          IS 'last-mile 재시도 횟수 (0 = 초회)';
COMMENT ON COLUMN t_ai_message.last_attempt_at      IS '마지막 last-mile publish 시각 — retry scheduler 가 timeout 판정에 사용';

CREATE INDEX IF NOT EXISTS idx_ai_message_from
    ON t_ai_message (from_agent_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_message_to
    ON t_ai_message (to_agent_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_message_reply
    ON t_ai_message (reply_to_message_id);
CREATE INDEX IF NOT EXISTS idx_ai_message_status
    ON t_ai_message (status, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_message_root
    ON t_ai_message (root_message_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_message_retry
    ON t_ai_message (status, last_attempt_at) WHERE status = 'sent';

-- =====================================================================
-- t_aidesk_setting — 런타임 변경 가능한 앱 단일 설정 (key-value)
-- 첫 항목: 'a2a_workspace' — 사내 동료 AI 와의 소통(kaflix-a2a/kaflix-channel MCP)
-- 권한이 활성화되는 워크스페이스 절대 경로. NULL 이면 (me) 터미널 열기 비활성.
-- =====================================================================
CREATE TABLE IF NOT EXISTS t_aidesk_setting (
    account_sn    BIGINT       NOT NULL REFERENCES t_user(account_sn) ON DELETE CASCADE,
    setting_key   VARCHAR(80)  NOT NULL,
    setting_value TEXT,
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (account_sn, setting_key)
);

COMMENT ON TABLE  t_aidesk_setting IS 'AI Desk 런타임 단일값 설정 (사용자별).';
COMMENT ON COLUMN t_aidesk_setting.account_sn    IS '소유 사용자 (t_user.account_sn).';
COMMENT ON COLUMN t_aidesk_setting.setting_key   IS '설정 키 (account_sn 과의 복합 PK)';
COMMENT ON COLUMN t_aidesk_setting.setting_value IS '설정값 (NULL 가능)';

-- =====================================================================
-- t_ai_action_log — AI 가 수행한 실제 mutation 액션 (Write/Edit/Bash/DB MCP 등)
-- 메시지(t_ai_message)와 결합해 "어떤 대화가 어떤 변경을 만들었나" 추적용.
-- Helper 가 PostToolUse 훅에서 POST /api/action-logs 로 기록.
-- =====================================================================
CREATE TABLE IF NOT EXISTS t_ai_action_log (
    log_id       VARCHAR(36)  PRIMARY KEY,
    agent_id     VARCHAR(36),
    agent_name   VARCHAR(50),
    session_id   VARCHAR(80),
    tool         VARCHAR(50)  NOT NULL,
    category     VARCHAR(20)  NOT NULL,
    target       VARCHAR(500),
    summary      VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  t_ai_action_log IS 'AI 가 수행한 mutation 액션 감사 로그';
COMMENT ON COLUMN t_ai_action_log.log_id      IS '액션 UUID (PK)';
COMMENT ON COLUMN t_ai_action_log.agent_id    IS '수행 에이전트 ID (식별 안되면 NULL)';
COMMENT ON COLUMN t_ai_action_log.agent_name  IS '비정규화 이름 (조회 성능)';
COMMENT ON COLUMN t_ai_action_log.session_id  IS 'Claude 세션 UUID';
COMMENT ON COLUMN t_ai_action_log.tool        IS 'Write / Edit / Bash / mcp__postgres__query 등';
COMMENT ON COLUMN t_ai_action_log.category    IS 'code | schema | file | command';
COMMENT ON COLUMN t_ai_action_log.target      IS '파일 경로 / 테이블 / 명령 요약';
COMMENT ON COLUMN t_ai_action_log.summary     IS '액션 요약 (사람 가독)';

CREATE INDEX IF NOT EXISTS idx_action_log_created_at
    ON t_ai_action_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_action_log_category
    ON t_ai_action_log (category, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_action_log_agent
    ON t_ai_action_log (agent_id, created_at DESC);
